name: atzos_assignment
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  flutter_bloc: ^8.1.5
  auto_size_text: ^3.0.0
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  build_runner: ^2.4.9
  copy_with_extension: ^5.0.4
  dio: ^5.4.2+1
  xml2json: ^6.2.3
  intl: ^0.19.0
  flutter_social_button: ^1.1.4+1
  font_awesome_flutter: ^10.7.0
  maps_launcher: ^2.2.1
  html: ^0.15.4
  url_launcher: ^6.2.6
  lottie: ^3.1.0
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Monsterrat
      fonts:
        - asset: font/Montserrat-Regular.ttf
        
    - family: Jet
      fonts:
        - asset: font/JetBrainsMonoNL-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
